//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibreria.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadisticas
    {
        public int idEstadisticas { get; set; }
        public Nullable<int> partidasJugadas { get; set; }
        public Nullable<int> partidasGanadas { get; set; }
        public Nullable<int> vecesTematicaMixto { get; set; }
        public Nullable<int> vecesTematicaAnimales { get; set; }
        public Nullable<int> vecesTematicaPaises { get; set; }
        public Nullable<int> vecesTematicaMitologia { get; set; }
        public Nullable<int> vecesTematicaEspacio { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
