//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibreria.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int idEstadisticas { get; set; }
        public Nullable<int> partidasJugadas { get; set; }
        public Nullable<int> partidasGanadas { get; set; }
        public Nullable<int> vecesTematicaMixto { get; set; }
        public Nullable<int> vecesTematicaAnimales { get; set; }
        public Nullable<int> vecesTematicaPaises { get; set; }
        public Nullable<int> vecesTematicaMitologia { get; set; }
        public Nullable<int> vecesTematicaEspacio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
