//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibreria.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expulsion
    {
        public int idExpulsion { get; set; }
        public string motivo { get; set; }
        public bool fuePenalizado { get; set; }
        public bool esHacker { get; set; }
        public int idUsuarioCuenta { get; set; }
    
        public virtual UsuarioCuenta UsuarioCuenta { get; set; }
    }
}
