//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibreria.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Amigoes = new HashSet<Amigo>();
            this.Amigoes1 = new HashSet<Amigo>();
            this.PeticionAmistads = new HashSet<PeticionAmistad>();
            this.PeticionAmistads1 = new HashSet<PeticionAmistad>();
        }
    
        public int idUsuario { get; set; }
        public string gamertag { get; set; }
        public byte[] fotoPerfil { get; set; }
        public Nullable<System.DateTime> ultimaConexion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amigo> Amigoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amigo> Amigoes1 { get; set; }
        public virtual Estadistica Estadistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeticionAmistad> PeticionAmistads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeticionAmistad> PeticionAmistads1 { get; set; }
        public virtual UsuarioCuenta UsuarioCuenta { get; set; }
    }
}
