//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibreria.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCuenta
    {
        public int idUsuarioCuenta { get; set; }
        public string gamertag { get; set; }
        public string hashContrasenia { get; set; }
        public string correo { get; set; }
    
        public virtual Expulsion Expulsion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Veto Veto { get; set; }
    }
}
