//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCliente.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string buttonAceptar {
            get {
                return ResourceManager.GetString("buttonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animales.
        /// </summary>
        public static string buttonAnimales {
            get {
                return ResourceManager.GetString("buttonAnimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string buttonCambiarContrasenia {
            get {
                return ResourceManager.GetString("buttonCambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar foto.
        /// </summary>
        public static string buttonCambiarFotoPerfil {
            get {
                return ResourceManager.GetString("buttonCambiarFotoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesion.
        /// </summary>
        public static string buttonCerrarSesion {
            get {
                return ResourceManager.GetString("buttonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar partida.
        /// </summary>
        public static string buttonConfigurarPartida {
            get {
                return ResourceManager.GetString("buttonConfigurarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar edición.
        /// </summary>
        public static string buttonConfirmarEdicion {
            get {
                return ResourceManager.GetString("buttonConfirmarEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala de espera.
        /// </summary>
        public static string buttonCrearSalaEspera {
            get {
                return ResourceManager.GetString("buttonCrearSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar usuario.
        /// </summary>
        public static string buttonEditarUsuario {
            get {
                return ResourceManager.GetString("buttonEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar partida.
        /// </summary>
        public static string buttonEmpezarPartida {
            get {
                return ResourceManager.GetString("buttonEmpezarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string buttonEnviar {
            get {
                return ResourceManager.GetString("buttonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No recibiste el código? Volver a enviar.
        /// </summary>
        public static string buttonenviarCodigoNuevamente {
            get {
                return ResourceManager.GetString("buttonenviarCodigoNuevamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string buttonExpulsar {
            get {
                return ResourceManager.GetString("buttonExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta que se acaben las cartas.
        /// </summary>
        public static string buttonFinCartas {
            get {
                return ResourceManager.GetString("buttonFinCartas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta que se acaben las rondas.
        /// </summary>
        public static string buttonFinRondas {
            get {
                return ResourceManager.GetString("buttonFinRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string buttonGuardarCambios {
            get {
                return ResourceManager.GetString("buttonGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string buttonIniciarSesion {
            get {
                return ResourceManager.GetString("buttonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar amigos.
        /// </summary>
        public static string buttonInvitaAmigos {
            get {
                return ResourceManager.GetString("buttonInvitaAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string buttonJugar {
            get {
                return ResourceManager.GetString("buttonJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string buttonJugarComoInvitado {
            get {
                return ResourceManager.GetString("buttonJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo!.
        /// </summary>
        public static string buttonListo {
            get {
                return ResourceManager.GetString("buttonListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mitología.
        /// </summary>
        public static string buttonMitologia {
            get {
                return ResourceManager.GetString("buttonMitologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixta.
        /// </summary>
        public static string buttonMixta {
            get {
                return ResourceManager.GetString("buttonMixta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string buttonOlvidarContrasenia {
            get {
                return ResourceManager.GetString("buttonOlvidarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Países.
        /// </summary>
        public static string buttonPaises {
            get {
                return ResourceManager.GetString("buttonPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string buttonRegistrarse {
            get {
                return ResourceManager.GetString("buttonRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string buttonRegresar {
            get {
                return ResourceManager.GetString("buttonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma.
        /// </summary>
        public static string buttonSeleccionarIdioma {
            get {
                return ResourceManager.GetString("buttonSeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala de espera.
        /// </summary>
        public static string buttonUnirseSalaDeEspera {
            get {
                return ResourceManager.GetString("buttonUnirseSalaDeEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos conectados.
        /// </summary>
        public static string labelAmigosConectados {
            get {
                return ResourceManager.GetString("labelAmigosConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos obligatorios.
        /// </summary>
        public static string labelCamposObligatorios {
            get {
                return ResourceManager.GetString("labelCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartas en la mesa.
        /// </summary>
        public static string labelCartasEnMesa {
            get {
                return ResourceManager.GetString("labelCartasEnMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de la sala: .
        /// </summary>
        public static string labelCodigoSala {
            get {
                return ResourceManager.GetString("labelCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición de victoria.
        /// </summary>
        public static string labelCondicionDeVictoria {
            get {
                return ResourceManager.GetString("labelCondicionDeVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de la partida.
        /// </summary>
        public static string labelConfiguracionPartida {
            get {
                return ResourceManager.GetString("labelConfiguracionPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string labelConfirmarContrasenia {
            get {
                return ResourceManager.GetString("labelConfirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string labelContrasenia {
            get {
                return ResourceManager.GetString("labelContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña anterior.
        /// </summary>
        public static string labelContraseniaAnterior {
            get {
                return ResourceManager.GetString("labelContraseniaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener:.
        /// </summary>
        public static string labelContraseniaInstruccion {
            get {
                return ResourceManager.GetString("labelContraseniaInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No más de 20 caracteres.
        /// </summary>
        public static string labelContraseniaMaximo {
            get {
                return ResourceManager.GetString("labelContraseniaMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 5 caracteres.
        /// </summary>
        public static string labelContraseniaMinimo {
            get {
                return ResourceManager.GetString("labelContraseniaMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 1 símbolo (!@#$%^&amp;*()).
        /// </summary>
        public static string labelContraseniaSimbolos {
            get {
                return ResourceManager.GetString("labelContraseniaSimbolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico.
        /// </summary>
        public static string labelCorreoE {
            get {
                return ResourceManager.GetString("labelCorreoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a los jugadores....
        /// </summary>
        public static string labelEsperandoJugadores {
            get {
                return ResourceManager.GetString("labelEsperandoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando pista....
        /// </summary>
        public static string labelEsperandoPista {
            get {
                return ResourceManager.GetString("labelEsperandoPista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código que le enviamos a su correo.
        /// </summary>
        public static string labelIngresarCodigoCorreo {
            get {
                return ResourceManager.GetString("labelIngresarCodigoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de sala.
        /// </summary>
        public static string labelIngresarCodigoSala {
            get {
                return ResourceManager.GetString("labelIngresarCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico.
        /// </summary>
        public static string labelIngresarCorreo {
            get {
                return ResourceManager.GetString("labelIngresarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu usuario.
        /// </summary>
        public static string labelIngresarUsuario {
            get {
                return ResourceManager.GetString("labelIngresarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string labelInicioSesion {
            get {
                return ResourceManager.GetString("labelInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Escoge la carta correcta en base a la pista!.
        /// </summary>
        public static string labelInstruccionPista {
            get {
                return ResourceManager.GetString("labelInstruccionPista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inválido.
        /// </summary>
        public static string labelInvalido {
            get {
                return ResourceManager.GetString("labelInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envíale a tus amigos una invitación.
        /// </summary>
        public static string labelInvitaAmigos {
            get {
                return ResourceManager.GetString("labelInvitaAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string labelListaAmigos {
            get {
                return ResourceManager.GetString("labelListaAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay solicitudes de amistad pendientes.
        /// </summary>
        public static string labelNoHaySolicitudes {
            get {
                return ResourceManager.GetString("labelNoHaySolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string labelNuevaContrasenia {
            get {
                return ResourceManager.GetString("labelNuevaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo en el juego?.
        /// </summary>
        public static string labelNuevoEnElJuego {
            get {
                return ResourceManager.GetString("labelNuevoEnElJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de rondas.
        /// </summary>
        public static string labelNumeroRondas {
            get {
                return ResourceManager.GetString("labelNumeroRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pista: .
        /// </summary>
        public static string labelPista {
            get {
                return ResourceManager.GetString("labelPista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita la contraseña.
        /// </summary>
        public static string labelRepitaContraseña {
            get {
                return ResourceManager.GetString("labelRepitaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda.
        /// </summary>
        public static string labelRonda {
            get {
                return ResourceManager.GetString("labelRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string labelSalaDeEspera {
            get {
                return ResourceManager.GetString("labelSalaDeEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una foto de perfil.
        /// </summary>
        public static string labelSeleccionarFotoPerfil {
            get {
                return ResourceManager.GetString("labelSeleccionarFotoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de solicitudes de amistad.
        /// </summary>
        public static string labelSolicitudesAmistad {
            get {
                return ResourceManager.GetString("labelSolicitudesAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temática.
        /// </summary>
        public static string labelTematica {
            get {
                return ResourceManager.GetString("labelTematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu mazo.
        /// </summary>
        public static string labelTuMazo {
            get {
                return ResourceManager.GetString("labelTuMazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios en la sala de espera.
        /// </summary>
        public static string labelUsuariosLobby {
            get {
                return ResourceManager.GetString("labelUsuariosLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios aplicados con éxito.
        /// </summary>
        public static string mensajeCambiosAplicadosExito {
            get {
                return ResourceManager.GetString("mensajeCambiosAplicadosExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden dejar campos vacíos.
        /// </summary>
        public static string mensajeCamposVacios {
            get {
                return ResourceManager.GetString("mensajeCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error y no se pudieron cargar los datos de tus amigos.
        /// </summary>
        public static string mensajeCargarAmigosFalla {
            get {
                return ResourceManager.GetString("mensajeCargarAmigosFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código copiado exitosamente en el portapapeles.
        /// </summary>
        public static string mensajeCodigoCopiado {
            get {
                return ResourceManager.GetString("mensajeCodigoCopiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea expulsar al jugador?.
        /// </summary>
        public static string mensajeConfirmacionExpulsion {
            get {
                return ResourceManager.GetString("mensajeConfirmacionExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar esa contraseña, usa una más segura.
        /// </summary>
        public static string mensajeContraseniaInsegura {
            get {
                return ResourceManager.GetString("mensajeContraseniaInsegura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas deben coincidir para continuar.
        /// </summary>
        public static string mensajeContraseniasNoCoinciden {
            get {
                return ResourceManager.GetString("mensajeContraseniasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No encontramos un usuario con el correo electrónico y el gamertag ingresados, intenta de nuevo.
        /// </summary>
        public static string mensajeCorreoYGamertagNoCoinciden {
            get {
                return ResourceManager.GetString("mensajeCorreoYGamertagNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezando ronda....
        /// </summary>
        public static string mensajeEmpezandoRonda {
            get {
                return ResourceManager.GetString("mensajeEmpezandoRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por el momento no se puedieron cargar las solicitudes de amistad, regrese mas tarde..
        /// </summary>
        public static string mensajeErrorAlCargarLasSolicitudesAmistad {
            get {
                return ResourceManager.GetString("mensajeErrorAlCargarLasSolicitudesAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al conectarse con la base de datos.
        /// </summary>
        public static string mensajeErrorBaseDatos {
            get {
                return ResourceManager.GetString("mensajeErrorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado, intente de nuevo más tarde.
        /// </summary>
        public static string mensajeErrorInesperado {
            get {
                return ResourceManager.GetString("mensajeErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer conexión con el servidor.
        /// </summary>
        public static string mensajeErrorServidor {
            get {
                return ResourceManager.GetString("mensajeErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escogiendo narrador....
        /// </summary>
        public static string mensajeEscogiendoNarrador {
            get {
                return ResourceManager.GetString("mensajeEscogiendoNarrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha configurado el idioma predeterminado.
        /// </summary>
        public static string mensajeIdiomaInvalido {
            get {
                return ResourceManager.GetString("mensajeIdiomaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen seleccionada es inválida o no se seleccionó correctamente.
        /// </summary>
        public static string mensajeImagenInvalida {
            get {
                return ResourceManager.GetString("mensajeImagenInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se seleccionaste ninguna imagen..
        /// </summary>
        public static string mensajeImagenNoSelecionadaEditar {
            get {
                return ResourceManager.GetString("mensajeImagenNoSelecionadaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen que seleccionaste es valida para el reemplazo, porfavor seleciona otra..
        /// </summary>
        public static string mensajeImagenReemplazoInvalida {
            get {
                return ResourceManager.GetString("mensajeImagenReemplazoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La invitación se envió correctamente.
        /// </summary>
        public static string mensajeInvitacionExitosa {
            get {
                return ResourceManager.GetString("mensajeInvitacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al enviar la invitación, intente de nuevo más tarde.
        /// </summary>
        public static string mensajeInvitacionFallida {
            get {
                return ResourceManager.GetString("mensajeInvitacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ya ha salido de la sala.
        /// </summary>
        public static string mensajeJugadorSaleDeSala {
            get {
                return ResourceManager.GetString("mensajeJugadorSaleDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby no disponible.
        /// </summary>
        public static string mensajeLobbyNoDisponible {
            get {
                return ResourceManager.GetString("mensajeLobbyNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de sala ingresado no se encontró.
        /// </summary>
        public static string mensajeLobbyNoEncontrado {
            get {
                return ResourceManager.GetString("mensajeLobbyNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes registrarte sin foto de perfil.
        /// </summary>
        public static string mensajeNoHayFotoDePerfil {
            get {
                return ResourceManager.GetString("mensajeNoHayFotoDePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se realizó ningún cambio.
        /// </summary>
        public static string mensajeNoHuboCambios {
            get {
                return ResourceManager.GetString("mensajeNoHuboCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROFE ESE TEXTO NO SE VALE.
        /// </summary>
        public static string mensajeProfe {
            get {
                return ResourceManager.GetString("mensajeProfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no se encuentra disponible.
        /// </summary>
        public static string mensajeServidorNoDisponible {
            get {
                return ResourceManager.GetString("mensajeServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no puede procesar solicitudes en este momento.
        /// </summary>
        public static string mensajeServidorSobrecargado {
            get {
                return ResourceManager.GetString("mensajeServidorSobrecargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si no eres tú quien inició sesión, por favor contacta a soporte..
        /// </summary>
        public static string mensajeSesionIniciada {
            get {
                return ResourceManager.GetString("mensajeSesionIniciada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptaste la solicitud de amistad de .
        /// </summary>
        public static string mensajeSolicitudAmistadAceptada {
            get {
                return ResourceManager.GetString("mensajeSolicitudAmistadAceptada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió correctamente la solicitud de amistad.
        /// </summary>
        public static string mensajeSolicitudAmistadExitosa {
            get {
                return ResourceManager.GetString("mensajeSolicitudAmistadExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazaste la solicitud de amistad de .
        /// </summary>
        public static string mensajeSolicitudAmistadRechazada {
            get {
                return ResourceManager.GetString("mensajeSolicitudAmistadRechazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña incorrectos.
        /// </summary>
        public static string mensajeUsuarioContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("mensajeUsuarioContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario editado con éxito.
        /// </summary>
        public static string mensajeUsuarioEditadoConExito {
            get {
                return ResourceManager.GetString("mensajeUsuarioEditadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al editar al usuario.
        /// </summary>
        public static string mensajeUsuarioEditadoFallo {
            get {
                return ResourceManager.GetString("mensajeUsuarioEditadoFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado con éxito.
        /// </summary>
        public static string mensajeUsuarioRegistradoConExito {
            get {
                return ResourceManager.GetString("mensajeUsuarioRegistradoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string menuItemEditarperfil {
            get {
                return ResourceManager.GetString("menuItemEditarperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver tus estadistícas.
        /// </summary>
        public static string menuItemEstadisticas {
            get {
                return ResourceManager.GetString("menuItemEstadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string menuItemPerfil {
            get {
                return ResourceManager.GetString("menuItemPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string tituloAmigos {
            get {
                return ResourceManager.GetString("tituloAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Describelo.
        /// </summary>
        public static string tituloBienvenida {
            get {
                return ResourceManager.GetString("tituloBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string tituloCambiarContrasenia {
            get {
                return ResourceManager.GetString("tituloCambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron cargar los datos.
        /// </summary>
        public static string tituloCargarAmigosFalla {
            get {
                return ResourceManager.GetString("tituloCargarAmigosFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código copiado.
        /// </summary>
        public static string tituloCodigoCopiado {
            get {
                return ResourceManager.GetString("tituloCodigoCopiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo y el gamertag no coinciden.
        /// </summary>
        public static string tituloCorreoYGamertagNoCoinciden {
            get {
                return ResourceManager.GetString("tituloCorreoYGamertagNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar usuario.
        /// </summary>
        public static string tituloEditarUsuario {
            get {
                return ResourceManager.GetString("tituloEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la base de datos.
        /// </summary>
        public static string tituloErrorBaseDatos {
            get {
                return ResourceManager.GetString("tituloErrorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cagar solicitudes de amistad.
        /// </summary>
        public static string tituloErrorCargarSolicitudesAmistad {
            get {
                return ResourceManager.GetString("tituloErrorCargarSolicitudesAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado.
        /// </summary>
        public static string tituloErrorInesperado {
            get {
                return ResourceManager.GetString("tituloErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor.
        /// </summary>
        public static string tituloErrorServidor {
            get {
                return ResourceManager.GetString("tituloErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de idioma inválida.
        /// </summary>
        public static string tituloIdiomaInvalido {
            get {
                return ResourceManager.GetString("tituloIdiomaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de reemplazo invalida.
        /// </summary>
        public static string tituloImagenCambioInvalida {
            get {
                return ResourceManager.GetString("tituloImagenCambioInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen inválida.
        /// </summary>
        public static string tituloImagenInvalida {
            get {
                return ResourceManager.GetString("tituloImagenInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen no seleccionada para edición .
        /// </summary>
        public static string tituloImagenNoSelecionadaEditar {
            get {
                return ResourceManager.GetString("tituloImagenNoSelecionadaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar código.
        /// </summary>
        public static string tituloIngresarCodigoCorreo {
            get {
                return ResourceManager.GetString("tituloIngresarCodigoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de la sala.
        /// </summary>
        public static string tituloIngresarCodigoSala {
            get {
                return ResourceManager.GetString("tituloIngresarCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar correo.
        /// </summary>
        public static string tituloIngresarCorreo {
            get {
                return ResourceManager.GetString("tituloIngresarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string tituloInicioSesion {
            get {
                return ResourceManager.GetString("tituloInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación a partida.
        /// </summary>
        public static string tituloInvitacionPartida {
            get {
                return ResourceManager.GetString("tituloInvitacionPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descríbelo.
        /// </summary>
        public static string tituloJuego {
            get {
                return ResourceManager.GetString("tituloJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby no encontrado.
        /// </summary>
        public static string tituloLobbyNoEncontrado {
            get {
                return ResourceManager.GetString("tituloLobbyNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string tituloRecuperarContrasenia {
            get {
                return ResourceManager.GetString("tituloRecuperarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar invitado.
        /// </summary>
        public static string tituloRegistrarInvitado {
            get {
                return ResourceManager.GetString("tituloRegistrarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar usuario.
        /// </summary>
        public static string tituloRegistroUsuario {
            get {
                return ResourceManager.GetString("tituloRegistroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string tituloSalaEspera {
            get {
                return ResourceManager.GetString("tituloSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has iniciado sesión.
        /// </summary>
        public static string tituloSesionIniciada {
            get {
                return ResourceManager.GetString("tituloSesionIniciada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad.
        /// </summary>
        public static string tituloSolicitudAmistad {
            get {
                return ResourceManager.GetString("tituloSolicitudAmistad", resourceCulture);
            }
        }
    }
}
