//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCliente.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string buttonAceptar {
            get {
                return ResourceManager.GetString("buttonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animales.
        /// </summary>
        public static string buttonAnimales {
            get {
                return ResourceManager.GetString("buttonAnimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string buttonCambiarContrasenia {
            get {
                return ResourceManager.GetString("buttonCambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string buttonCerrarSesion {
            get {
                return ResourceManager.GetString("buttonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar partida.
        /// </summary>
        public static string buttonConfigurarPartida {
            get {
                return ResourceManager.GetString("buttonConfigurarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar edición.
        /// </summary>
        public static string buttonConfirmarEdicion {
            get {
                return ResourceManager.GetString("buttonConfirmarEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar usuario.
        /// </summary>
        public static string buttonEditarUsuario {
            get {
                return ResourceManager.GetString("buttonEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar partida.
        /// </summary>
        public static string buttonEmpezarPartida {
            get {
                return ResourceManager.GetString("buttonEmpezarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string buttonExpulsar {
            get {
                return ResourceManager.GetString("buttonExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string buttonIniciarSesion {
            get {
                return ResourceManager.GetString("buttonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string buttonJugarComoInvitado {
            get {
                return ResourceManager.GetString("buttonJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MItología.
        /// </summary>
        public static string buttonMitologia {
            get {
                return ResourceManager.GetString("buttonMitologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixta.
        /// </summary>
        public static string buttonMixta {
            get {
                return ResourceManager.GetString("buttonMixta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string buttonOlvidarContrasenia {
            get {
                return ResourceManager.GetString("buttonOlvidarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Países.
        /// </summary>
        public static string buttonPaises {
            get {
                return ResourceManager.GetString("buttonPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string buttonRegistrarse {
            get {
                return ResourceManager.GetString("buttonRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string buttonRegresar {
            get {
                return ResourceManager.GetString("buttonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma.
        /// </summary>
        public static string buttonSeleccionarIdioma {
            get {
                return ResourceManager.GetString("buttonSeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala de espera.
        /// </summary>
        public static string buttonUnirseSalaDeEspera {
            get {
                return ResourceManager.GetString("buttonUnirseSalaDeEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos conectados.
        /// </summary>
        public static string labelAmigosConectados {
            get {
                return ResourceManager.GetString("labelAmigosConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios aplicados con éxito.
        /// </summary>
        public static string labelCambiosAplicadosExito {
            get {
                return ResourceManager.GetString("labelCambiosAplicadosExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden dejar campos vacíos.
        /// </summary>
        public static string labelCamposVacios {
            get {
                return ResourceManager.GetString("labelCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartas en la mesa.
        /// </summary>
        public static string labelCartasEnMesa {
            get {
                return ResourceManager.GetString("labelCartasEnMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición de victoria.
        /// </summary>
        public static string labelCondicionDeVictoria {
            get {
                return ResourceManager.GetString("labelCondicionDeVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de la partida.
        /// </summary>
        public static string labelConfiguracionPartida {
            get {
                return ResourceManager.GetString("labelConfiguracionPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea expulsar al jugador?.
        /// </summary>
        public static string labelConfirmacionExpulsion {
            get {
                return ResourceManager.GetString("labelConfirmacionExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string labelConfirmarContrasenia {
            get {
                return ResourceManager.GetString("labelConfirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string labelContrasenia {
            get {
                return ResourceManager.GetString("labelContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña anterior.
        /// </summary>
        public static string labelContraseniaAnterior {
            get {
                return ResourceManager.GetString("labelContraseniaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña editada con éxito.
        /// </summary>
        public static string labelContraseniaEditadaConExito {
            get {
                return ResourceManager.GetString("labelContraseniaEditadaConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar esa contraseña, usa una más segura.
        /// </summary>
        public static string labelContraseniaInsegura {
            get {
                return ResourceManager.GetString("labelContraseniaInsegura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas deben coincidir para continuar.
        /// </summary>
        public static string labelContraseniasNoCoinciden {
            get {
                return ResourceManager.GetString("labelContraseniasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string labelInicioSesion {
            get {
                return ResourceManager.GetString("labelInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ya ha salido de la sala.
        /// </summary>
        public static string labelJugadorSaleDeSala {
            get {
                return ResourceManager.GetString("labelJugadorSaleDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes registrarte sin foto de perfil.
        /// </summary>
        public static string labelNoHayFotoDePerfil {
            get {
                return ResourceManager.GetString("labelNoHayFotoDePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string labelNuevaContrasenia {
            get {
                return ResourceManager.GetString("labelNuevaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo en el juego?.
        /// </summary>
        public static string labelNuevoEnElJuego {
            get {
                return ResourceManager.GetString("labelNuevoEnElJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda.
        /// </summary>
        public static string labelRonda {
            get {
                return ResourceManager.GetString("labelRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string labelSalaDeEspera {
            get {
                return ResourceManager.GetString("labelSalaDeEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una foto de perfil.
        /// </summary>
        public static string labelSeleccionarFotoPerfil {
            get {
                return ResourceManager.GetString("labelSeleccionarFotoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no se encuentra disponible.
        /// </summary>
        public static string labelServidorNoDisponible {
            get {
                return ResourceManager.GetString("labelServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no puede procesar solicitudes en este momento.
        /// </summary>
        public static string labelServidorSobrecargado {
            get {
                return ResourceManager.GetString("labelServidorSobrecargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temática.
        /// </summary>
        public static string labelTematica {
            get {
                return ResourceManager.GetString("labelTematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu mazo.
        /// </summary>
        public static string labelTuMazo {
            get {
                return ResourceManager.GetString("labelTuMazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña incorrectos.
        /// </summary>
        public static string labelUsuarioContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("labelUsuarioContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario editado con éxito.
        /// </summary>
        public static string labelUsuarioEditadoConExito {
            get {
                return ResourceManager.GetString("labelUsuarioEditadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado con éxito.
        /// </summary>
        public static string labelUsuarioRegistradoConExito {
            get {
                return ResourceManager.GetString("labelUsuarioRegistradoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Describelo.
        /// </summary>
        public static string tituloBienvenida {
            get {
                return ResourceManager.GetString("tituloBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string tituloInicioSesion {
            get {
                return ResourceManager.GetString("tituloInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar invitado.
        /// </summary>
        public static string tituloRegistrarInvitado {
            get {
                return ResourceManager.GetString("tituloRegistrarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar usuario.
        /// </summary>
        public static string tituloRegistroUsuario {
            get {
                return ResourceManager.GetString("tituloRegistroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string tituloSalaEspera {
            get {
                return ResourceManager.GetString("tituloSalaEspera", resourceCulture);
            }
        }
    }
}
