//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCliente.ServidorDescribelo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioContexto", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCliente.ServidorDescribelo.Usuario))]
    public partial class UsuarioContexto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.FileStream))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.MemoryStream))]
    public partial class Usuario : WpfCliente.ServidorDescribelo.UsuarioContexto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaHASHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsInvitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream FotoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaHASH {
            get {
                return this.ContraseniaHASHField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaHASHField, value) != true)) {
                    this.ContraseniaHASHField = value;
                    this.RaisePropertyChanged("ContraseniaHASH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsInvitado {
            get {
                return this.EsInvitadoField;
            }
            set {
                if ((this.EsInvitadoField.Equals(value) != true)) {
                    this.EsInvitadoField = value;
                    this.RaisePropertyChanged("EsInvitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream FotoUsuario {
            get {
                return this.FotoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoUsuarioField, value) != true)) {
                    this.FotoUsuarioField = value;
                    this.RaisePropertyChanged("FotoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amigo", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.FileStream))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.MemoryStream))]
    public partial class Amigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.EstadoAmigo EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.EstadoAmigo Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoAmigo", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Enumerador")]
    public enum EstadoAmigo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conectado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desconectado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Solicitud = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActualizarEstado = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistad", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.Usuario RemitenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.Usuario Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioFalla", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class UsuarioFalla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaConectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExisteUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaConectado {
            get {
                return this.EstaConectadoField;
            }
            set {
                if ((this.EstaConectadoField.Equals(value) != true)) {
                    this.EstaConectadoField = value;
                    this.RaisePropertyChanged("EstaConectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExisteUsuario {
            get {
                return this.ExisteUsuarioField;
            }
            set {
                if ((this.ExisteUsuarioField.Equals(value) != true)) {
                    this.ExisteUsuarioField = value;
                    this.RaisePropertyChanged("ExisteUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMensaje", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class ChatMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoraFecha {
            get {
                return this.HoraFechaField;
            }
            set {
                if ((this.HoraFechaField.Equals(value) != true)) {
                    this.HoraFechaField = value;
                    this.RaisePropertyChanged("HoraFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfiguracionPartida", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class ConfiguracionPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.CondicionVictoriaPartida CondicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroRondasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.TematicaPartida TematicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.CondicionVictoriaPartida Condicion {
            get {
                return this.CondicionField;
            }
            set {
                if ((this.CondicionField.Equals(value) != true)) {
                    this.CondicionField = value;
                    this.RaisePropertyChanged("Condicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroRondas {
            get {
                return this.NumeroRondasField;
            }
            set {
                if ((this.NumeroRondasField.Equals(value) != true)) {
                    this.NumeroRondasField = value;
                    this.RaisePropertyChanged("NumeroRondas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.TematicaPartida Tematica {
            get {
                return this.TematicaField;
            }
            set {
                if ((this.TematicaField.Equals(value) != true)) {
                    this.TematicaField = value;
                    this.RaisePropertyChanged("Tematica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CondicionVictoriaPartida", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Enumerador")]
    public enum CondicionVictoriaPartida : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorCartasAgotadas = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorCantidadRondas = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TematicaPartida", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Enumerador")]
    public enum TematicaPartida : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mixta = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Animales = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paises = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mitologia = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImagenCarta", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class ImagenCarta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.MemoryStream ImagenStreamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdImagen {
            get {
                return this.IdImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdImagenField, value) != true)) {
                    this.IdImagenField = value;
                    this.RaisePropertyChanged("IdImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.MemoryStream ImagenStream {
            get {
                return this.ImagenStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenStreamField, value) != true)) {
                    this.ImagenStreamField = value;
                    this.RaisePropertyChanged("ImagenStream");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadisticasPartida", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class EstadisticasPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.JugadorEstadisticas[] JugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.JugadorEstadisticas PrimerLugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.JugadorEstadisticas SegundoLugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.TematicaPartida TematicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.JugadorEstadisticas TercerLugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRondasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.JugadorEstadisticas[] Jugadores {
            get {
                return this.JugadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresField, value) != true)) {
                    this.JugadoresField = value;
                    this.RaisePropertyChanged("Jugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.JugadorEstadisticas PrimerLugar {
            get {
                return this.PrimerLugarField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerLugarField, value) != true)) {
                    this.PrimerLugarField = value;
                    this.RaisePropertyChanged("PrimerLugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.JugadorEstadisticas SegundoLugar {
            get {
                return this.SegundoLugarField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoLugarField, value) != true)) {
                    this.SegundoLugarField = value;
                    this.RaisePropertyChanged("SegundoLugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.TematicaPartida Tematica {
            get {
                return this.TematicaField;
            }
            set {
                if ((this.TematicaField.Equals(value) != true)) {
                    this.TematicaField = value;
                    this.RaisePropertyChanged("Tematica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.JugadorEstadisticas TercerLugar {
            get {
                return this.TercerLugarField;
            }
            set {
                if ((object.ReferenceEquals(this.TercerLugarField, value) != true)) {
                    this.TercerLugarField = value;
                    this.RaisePropertyChanged("TercerLugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRondas {
            get {
                return this.TotalRondasField;
            }
            set {
                if ((this.TotalRondasField.Equals(value) != true)) {
                    this.TotalRondasField = value;
                    this.RaisePropertyChanged("TotalRondas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorEstadisticas", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class JugadorEstadisticas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvitacionPartida", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class InvitacionPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GamertagEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GamertagReceptorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSala {
            get {
                return this.CodigoSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSalaField, value) != true)) {
                    this.CodigoSalaField = value;
                    this.RaisePropertyChanged("CodigoSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GamertagEmisor {
            get {
                return this.GamertagEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.GamertagEmisorField, value) != true)) {
                    this.GamertagEmisorField = value;
                    this.RaisePropertyChanged("GamertagEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GamertagReceptor {
            get {
                return this.GamertagReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.GamertagReceptorField, value) != true)) {
                    this.GamertagReceptorField = value;
                    this.RaisePropertyChanged("GamertagReceptor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Enumerador")]
    public enum EstadoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desconectado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conectado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disponible = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnSala = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnPartida = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDatosFalla", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo.Excepciones")]
    [System.SerializableAttribute()]
    public partial class BaseDatosFalla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsGamertagDuplicadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsGamertagDuplicado {
            get {
                return this.EsGamertagDuplicadoField;
            }
            set {
                if ((this.EsGamertagDuplicadoField.Equals(value) != true)) {
                    this.EsGamertagDuplicadoField = value;
                    this.RaisePropertyChanged("EsGamertagDuplicado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioAmistad", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioAmistadCallback))]
    public interface IServicioAmistad {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioAmistad/AbrirCanalParaPeticiones")]
        void AbrirCanalParaPeticiones(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioAmistad/AbrirCanalParaPeticiones")]
        System.Threading.Tasks.Task AbrirCanalParaPeticionesAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmistad/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IServicioAmistad/EnviarSolicitudAmistadResponse")]
        void EnviarSolicitudAmistad(WpfCliente.ServidorDescribelo.Usuario usuarioRemitente, string destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmistad/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IServicioAmistad/EnviarSolicitudAmistadResponse")]
        System.Threading.Tasks.Task EnviarSolicitudAmistadAsync(WpfCliente.ServidorDescribelo.Usuario usuarioRemitente, string destinatario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAmistadCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmistad/CambiarEstadoAmigo", ReplyAction="http://tempuri.org/IServicioAmistad/CambiarEstadoAmigoResponse")]
        void CambiarEstadoAmigo(WpfCliente.ServidorDescribelo.Amigo amigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmistad/ObtenerAmigoCallback", ReplyAction="http://tempuri.org/IServicioAmistad/ObtenerAmigoCallbackResponse")]
        void ObtenerAmigoCallback(WpfCliente.ServidorDescribelo.Amigo amigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmistad/ObtenerPeticionAmistadCallback", ReplyAction="http://tempuri.org/IServicioAmistad/ObtenerPeticionAmistadCallbackResponse")]
        void ObtenerPeticionAmistadCallback(WpfCliente.ServidorDescribelo.SolicitudAmistad nuevaSolicitudAmistad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAmistadChannel : WpfCliente.ServidorDescribelo.IServicioAmistad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAmistadClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioAmistad>, WpfCliente.ServidorDescribelo.IServicioAmistad {
        
        public ServicioAmistadClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioAmistadClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioAmistadClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAmistadClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAmistadClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AbrirCanalParaPeticiones(WpfCliente.ServidorDescribelo.Usuario usuario) {
            base.Channel.AbrirCanalParaPeticiones(usuario);
        }
        
        public System.Threading.Tasks.Task AbrirCanalParaPeticionesAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.AbrirCanalParaPeticionesAsync(usuario);
        }
        
        public void EnviarSolicitudAmistad(WpfCliente.ServidorDescribelo.Usuario usuarioRemitente, string destinatario) {
            base.Channel.EnviarSolicitudAmistad(usuarioRemitente, destinatario);
        }
        
        public System.Threading.Tasks.Task EnviarSolicitudAmistadAsync(WpfCliente.ServidorDescribelo.Usuario usuarioRemitente, string destinatario) {
            return base.Channel.EnviarSolicitudAmistadAsync(usuarioRemitente, destinatario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioChat")]
    public interface IServicioChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/CrearChat", ReplyAction="http://tempuri.org/IServicioChat/CrearChatResponse")]
        bool CrearChat(string idChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/CrearChat", ReplyAction="http://tempuri.org/IServicioChat/CrearChatResponse")]
        System.Threading.Tasks.Task<bool> CrearChatAsync(string idChat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatChannel : WpfCliente.ServidorDescribelo.IServicioChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioChat>, WpfCliente.ServidorDescribelo.IServicioChat {
        
        public ServicioChatClient() {
        }
        
        public ServicioChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearChat(string idChat) {
            return base.Channel.CrearChat(idChat);
        }
        
        public System.Threading.Tasks.Task<bool> CrearChatAsync(string idChat) {
            return base.Channel.CrearChatAsync(idChat);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioChatMotor", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioChatMotorCallback))]
    public interface IServicioChatMotor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/AgregarUsuarioChat", ReplyAction="http://tempuri.org/IServicioChatMotor/AgregarUsuarioChatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfCliente.ServidorDescribelo.UsuarioFalla), Action="http://tempuri.org/IServicioChatMotor/AgregarUsuarioChatUsuarioFallaFault", Name="UsuarioFalla", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
        bool AgregarUsuarioChat(string idChat, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/AgregarUsuarioChat", ReplyAction="http://tempuri.org/IServicioChatMotor/AgregarUsuarioChatResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioChatAsync(string idChat, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/DesconectarUsuarioChat", ReplyAction="http://tempuri.org/IServicioChatMotor/DesconectarUsuarioChatResponse")]
        bool DesconectarUsuarioChat(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/DesconectarUsuarioChat", ReplyAction="http://tempuri.org/IServicioChatMotor/DesconectarUsuarioChatResponse")]
        System.Threading.Tasks.Task<bool> DesconectarUsuarioChatAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/EnviarMensaje", ReplyAction="http://tempuri.org/IServicioChatMotor/EnviarMensajeResponse")]
        void EnviarMensaje(string idChat, WpfCliente.ServidorDescribelo.ChatMensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChatMotor/EnviarMensaje", ReplyAction="http://tempuri.org/IServicioChatMotor/EnviarMensajeResponse")]
        System.Threading.Tasks.Task EnviarMensajeAsync(string idChat, WpfCliente.ServidorDescribelo.ChatMensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatMotorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChatMotor/RecibirMensajeCliente")]
        void RecibirMensajeCliente(WpfCliente.ServidorDescribelo.ChatMensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatMotorChannel : WpfCliente.ServidorDescribelo.IServicioChatMotor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatMotorClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioChatMotor>, WpfCliente.ServidorDescribelo.IServicioChatMotor {
        
        public ServicioChatMotorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioChatMotorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioChatMotorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatMotorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatMotorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool AgregarUsuarioChat(string idChat, string nombreUsuario) {
            return base.Channel.AgregarUsuarioChat(idChat, nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioChatAsync(string idChat, string nombreUsuario) {
            return base.Channel.AgregarUsuarioChatAsync(idChat, nombreUsuario);
        }
        
        public bool DesconectarUsuarioChat(string nombreUsuario) {
            return base.Channel.DesconectarUsuarioChat(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> DesconectarUsuarioChatAsync(string nombreUsuario) {
            return base.Channel.DesconectarUsuarioChatAsync(nombreUsuario);
        }
        
        public void EnviarMensaje(string idChat, WpfCliente.ServidorDescribelo.ChatMensaje mensaje) {
            base.Channel.EnviarMensaje(idChat, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(string idChat, WpfCliente.ServidorDescribelo.ChatMensaje mensaje) {
            return base.Channel.EnviarMensajeAsync(idChat, mensaje);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioCorreo")]
    public interface IServicioCorreo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCorreo", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCorreoResponse")]
        bool VerificarCorreo(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCorreo", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCorreoResponse")]
        System.Threading.Tasks.Task<bool> VerificarCorreoAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCodigo", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCodigoResponse")]
        bool VerificarCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCodigo", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCodigoResponse")]
        System.Threading.Tasks.Task<bool> VerificarCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCorreoConGamertag", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCorreoConGamertagResponse")]
        bool VerificarCorreoConGamertag(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/VerificarCorreoConGamertag", ReplyAction="http://tempuri.org/IServicioCorreo/VerificarCorreoConGamertagResponse")]
        System.Threading.Tasks.Task<bool> VerificarCorreoConGamertagAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCorreoChannel : WpfCliente.ServidorDescribelo.IServicioCorreo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCorreoClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioCorreo>, WpfCliente.ServidorDescribelo.IServicioCorreo {
        
        public ServicioCorreoClient() {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerificarCorreo(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.VerificarCorreo(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCorreoAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.VerificarCorreoAsync(usuario);
        }
        
        public bool VerificarCodigo(string codigo) {
            return base.Channel.VerificarCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCodigoAsync(string codigo) {
            return base.Channel.VerificarCodigoAsync(codigo);
        }
        
        public bool VerificarCorreoConGamertag(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.VerificarCorreoConGamertag(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCorreoConGamertagAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.VerificarCorreoConGamertagAsync(usuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioPartida")]
    public interface IServicioPartida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/CrearPartida", ReplyAction="http://tempuri.org/IServicioPartida/CrearPartidaResponse")]
        string CrearPartida(string anfitrion, WpfCliente.ServidorDescribelo.ConfiguracionPartida configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/CrearPartida", ReplyAction="http://tempuri.org/IServicioPartida/CrearPartidaResponse")]
        System.Threading.Tasks.Task<string> CrearPartidaAsync(string anfitrion, WpfCliente.ServidorDescribelo.ConfiguracionPartida configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/ValidarPartida", ReplyAction="http://tempuri.org/IServicioPartida/ValidarPartidaResponse")]
        bool ValidarPartida(string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/ValidarPartida", ReplyAction="http://tempuri.org/IServicioPartida/ValidarPartidaResponse")]
        System.Threading.Tasks.Task<bool> ValidarPartidaAsync(string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/EsPartidaEmpezada", ReplyAction="http://tempuri.org/IServicioPartida/EsPartidaEmpezadaResponse")]
        bool EsPartidaEmpezada(string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartida/EsPartidaEmpezada", ReplyAction="http://tempuri.org/IServicioPartida/EsPartidaEmpezadaResponse")]
        System.Threading.Tasks.Task<bool> EsPartidaEmpezadaAsync(string idPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPartidaChannel : WpfCliente.ServidorDescribelo.IServicioPartida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPartidaClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioPartida>, WpfCliente.ServidorDescribelo.IServicioPartida {
        
        public ServicioPartidaClient() {
        }
        
        public ServicioPartidaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPartidaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPartidaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPartidaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CrearPartida(string anfitrion, WpfCliente.ServidorDescribelo.ConfiguracionPartida configuracion) {
            return base.Channel.CrearPartida(anfitrion, configuracion);
        }
        
        public System.Threading.Tasks.Task<string> CrearPartidaAsync(string anfitrion, WpfCliente.ServidorDescribelo.ConfiguracionPartida configuracion) {
            return base.Channel.CrearPartidaAsync(anfitrion, configuracion);
        }
        
        public bool ValidarPartida(string idPartida) {
            return base.Channel.ValidarPartida(idPartida);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarPartidaAsync(string idPartida) {
            return base.Channel.ValidarPartidaAsync(idPartida);
        }
        
        public bool EsPartidaEmpezada(string idPartida) {
            return base.Channel.EsPartidaEmpezada(idPartida);
        }
        
        public System.Threading.Tasks.Task<bool> EsPartidaEmpezadaAsync(string idPartida) {
            return base.Channel.EsPartidaEmpezadaAsync(idPartida);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioPartidaSesion", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioPartidaSesionCallback))]
    public interface IServicioPartidaSesion {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/UnirsePartida")]
        void UnirsePartida(string gamertag, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/UnirsePartida")]
        System.Threading.Tasks.Task UnirsePartidaAsync(string gamertag, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/ConfirmarMovimiento")]
        void ConfirmarMovimiento(string nombreJugador, string idPartida, string claveImagen, string pista);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/ConfirmarMovimiento")]
        System.Threading.Tasks.Task ConfirmarMovimientoAsync(string nombreJugador, string idPartida, string claveImagen, string pista);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/ExpulsarJugador")]
        void ExpulsarJugador(string nombreJugador, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/ExpulsarJugador")]
        System.Threading.Tasks.Task ExpulsarJugadorAsync(string nombreJugador, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartidaSesion/SolicitarImagenCarta", ReplyAction="http://tempuri.org/IServicioPartidaSesion/SolicitarImagenCartaResponse")]
        bool SolicitarImagenCarta(string nombreJugador, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartidaSesion/SolicitarImagenCarta", ReplyAction="http://tempuri.org/IServicioPartidaSesion/SolicitarImagenCartaResponse")]
        System.Threading.Tasks.Task<bool> SolicitarImagenCartaAsync(string nombreJugador, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/EmpezarPartida")]
        void EmpezarPartida(string nombreJugador, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/EmpezarPartida")]
        System.Threading.Tasks.Task EmpezarPartidaAsync(string nombreJugador, string idPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPartidaSesionCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartidaSesion/IniciarValoresPartidaCallback", ReplyAction="http://tempuri.org/IServicioPartidaSesion/IniciarValoresPartidaCallbackResponse")]
        void IniciarValoresPartidaCallback(bool seUnio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartidaSesion/AvanzarRondaCallback", ReplyAction="http://tempuri.org/IServicioPartidaSesion/AvanzarRondaCallbackResponse")]
        void AvanzarRondaCallback(int RondaActual);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/TurnoPerdidoCallback")]
        void TurnoPerdidoCallback();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/RecibirImagenCallback")]
        void RecibirImagenCallback(WpfCliente.ServidorDescribelo.ImagenCarta imagen);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/RecibirGrupoImagenCallback")]
        void RecibirGrupoImagenCallback(WpfCliente.ServidorDescribelo.ImagenCarta imagen);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/FinalizarPartida")]
        void FinalizarPartida();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/ObtenerJugadorPartidaCallback")]
        void ObtenerJugadorPartidaCallback(WpfCliente.ServidorDescribelo.Usuario jugardoreNuevoEnSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/EliminarJugadorPartidaCallback")]
        void EliminarJugadorPartidaCallback(WpfCliente.ServidorDescribelo.Usuario jugardoreRetiradoDeSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/NotificarNarradorCallback")]
        void NotificarNarradorCallback(bool esNarrador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/MostrarPistaCallback")]
        void MostrarPistaCallback(string pista);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioPartidaSesion/EnviarEstadisticas")]
        void EnviarEstadisticas(WpfCliente.ServidorDescribelo.EstadisticasPartida estadisticas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPartidaSesion/CambiarPantallaCallback", ReplyAction="http://tempuri.org/IServicioPartidaSesion/CambiarPantallaCallbackResponse")]
        void CambiarPantallaCallback(int numeroPantalla);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPartidaSesionChannel : WpfCliente.ServidorDescribelo.IServicioPartidaSesion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPartidaSesionClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioPartidaSesion>, WpfCliente.ServidorDescribelo.IServicioPartidaSesion {
        
        public ServicioPartidaSesionClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioPartidaSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioPartidaSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPartidaSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPartidaSesionClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UnirsePartida(string gamertag, string idPartida) {
            base.Channel.UnirsePartida(gamertag, idPartida);
        }
        
        public System.Threading.Tasks.Task UnirsePartidaAsync(string gamertag, string idPartida) {
            return base.Channel.UnirsePartidaAsync(gamertag, idPartida);
        }
        
        public void ConfirmarMovimiento(string nombreJugador, string idPartida, string claveImagen, string pista) {
            base.Channel.ConfirmarMovimiento(nombreJugador, idPartida, claveImagen, pista);
        }
        
        public System.Threading.Tasks.Task ConfirmarMovimientoAsync(string nombreJugador, string idPartida, string claveImagen, string pista) {
            return base.Channel.ConfirmarMovimientoAsync(nombreJugador, idPartida, claveImagen, pista);
        }
        
        public void ExpulsarJugador(string nombreJugador, string idPartida) {
            base.Channel.ExpulsarJugador(nombreJugador, idPartida);
        }
        
        public System.Threading.Tasks.Task ExpulsarJugadorAsync(string nombreJugador, string idPartida) {
            return base.Channel.ExpulsarJugadorAsync(nombreJugador, idPartida);
        }
        
        public bool SolicitarImagenCarta(string nombreJugador, string idPartida) {
            return base.Channel.SolicitarImagenCarta(nombreJugador, idPartida);
        }
        
        public System.Threading.Tasks.Task<bool> SolicitarImagenCartaAsync(string nombreJugador, string idPartida) {
            return base.Channel.SolicitarImagenCartaAsync(nombreJugador, idPartida);
        }
        
        public void EmpezarPartida(string nombreJugador, string idPartida) {
            base.Channel.EmpezarPartida(nombreJugador, idPartida);
        }
        
        public System.Threading.Tasks.Task EmpezarPartidaAsync(string nombreJugador, string idPartida) {
            return base.Channel.EmpezarPartidaAsync(nombreJugador, idPartida);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioRegistro")]
    public interface IServicioRegistro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistro/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistro/RegistrarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfCliente.ServidorDescribelo.BaseDatosFalla), Action="http://tempuri.org/IServicioRegistro/RegistrarUsuarioBaseDatosFallaFault", Name="BaseDatosFalla", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo.Excepciones")]
        bool RegistrarUsuario(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistro/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistro/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRegistroChannel : WpfCliente.ServidorDescribelo.IServicioRegistro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistroClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioRegistro>, WpfCliente.ServidorDescribelo.IServicioRegistro {
        
        public ServicioRegistroClient() {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarUsuario(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioSala")]
    public interface IServicioSala {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSala/CrearSala", ReplyAction="http://tempuri.org/IServicioSala/CrearSalaResponse")]
        string CrearSala(string nombreUsuarioAnfitrion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSala/CrearSala", ReplyAction="http://tempuri.org/IServicioSala/CrearSalaResponse")]
        System.Threading.Tasks.Task<string> CrearSalaAsync(string nombreUsuarioAnfitrion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSala/ValidarSala", ReplyAction="http://tempuri.org/IServicioSala/ValidarSalaResponse")]
        bool ValidarSala(string idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSala/ValidarSala", ReplyAction="http://tempuri.org/IServicioSala/ValidarSalaResponse")]
        System.Threading.Tasks.Task<bool> ValidarSalaAsync(string idSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSalaChannel : WpfCliente.ServidorDescribelo.IServicioSala, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSalaClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioSala>, WpfCliente.ServidorDescribelo.IServicioSala {
        
        public ServicioSalaClient() {
        }
        
        public ServicioSalaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSalaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSalaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSalaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CrearSala(string nombreUsuarioAnfitrion) {
            return base.Channel.CrearSala(nombreUsuarioAnfitrion);
        }
        
        public System.Threading.Tasks.Task<string> CrearSalaAsync(string nombreUsuarioAnfitrion) {
            return base.Channel.CrearSalaAsync(nombreUsuarioAnfitrion);
        }
        
        public bool ValidarSala(string idSala) {
            return base.Channel.ValidarSala(idSala);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarSalaAsync(string idSala) {
            return base.Channel.ValidarSalaAsync(idSala);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioSalaJugador", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioSalaJugadorCallback))]
    public interface IServicioSalaJugador {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSalaJugador/AgregarJugadorSala")]
        void AgregarJugadorSala(string gamertag, string idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSalaJugador/AgregarJugadorSala")]
        System.Threading.Tasks.Task AgregarJugadorSalaAsync(string gamertag, string idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSalaJugador/ComenzarPartidaAnfrition")]
        void ComenzarPartidaAnfrition(string nombre, string idSala, string idPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSalaJugador/ComenzarPartidaAnfrition")]
        System.Threading.Tasks.Task ComenzarPartidaAnfritionAsync(string nombre, string idSala, string idPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSalaJugadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalaJugador/ObtenerJugadorSalaCallback", ReplyAction="http://tempuri.org/IServicioSalaJugador/ObtenerJugadorSalaCallbackResponse")]
        void ObtenerJugadorSalaCallback(WpfCliente.ServidorDescribelo.Usuario jugardoreNuevoEnSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalaJugador/EliminarJugadorSalaCallback", ReplyAction="http://tempuri.org/IServicioSalaJugador/EliminarJugadorSalaCallbackResponse")]
        void EliminarJugadorSalaCallback(WpfCliente.ServidorDescribelo.Usuario jugardoreRetiradoDeSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSalaJugador/EmpezarPartidaCallBack")]
        void EmpezarPartidaCallBack(string idPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSalaJugadorChannel : WpfCliente.ServidorDescribelo.IServicioSalaJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSalaJugadorClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioSalaJugador>, WpfCliente.ServidorDescribelo.IServicioSalaJugador {
        
        public ServicioSalaJugadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioSalaJugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioSalaJugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSalaJugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSalaJugadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AgregarJugadorSala(string gamertag, string idSala) {
            base.Channel.AgregarJugadorSala(gamertag, idSala);
        }
        
        public System.Threading.Tasks.Task AgregarJugadorSalaAsync(string gamertag, string idSala) {
            return base.Channel.AgregarJugadorSalaAsync(gamertag, idSala);
        }
        
        public void ComenzarPartidaAnfrition(string nombre, string idSala, string idPartida) {
            base.Channel.ComenzarPartidaAnfrition(nombre, idSala, idPartida);
        }
        
        public System.Threading.Tasks.Task ComenzarPartidaAnfritionAsync(string nombre, string idSala, string idPartida) {
            return base.Channel.ComenzarPartidaAnfritionAsync(nombre, idSala, idPartida);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/EditarUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/EditarUsuarioResponse")]
        bool EditarUsuario(WpfCliente.ServidorDescribelo.Usuario usuarioEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/EditarUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EditarUsuarioAsync(WpfCliente.ServidorDescribelo.Usuario usuarioEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/YaIniciadoSesion", ReplyAction="http://tempuri.org/IServicioUsuario/YaIniciadoSesionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfCliente.ServidorDescribelo.UsuarioFalla), Action="http://tempuri.org/IServicioUsuario/YaIniciadoSesionUsuarioFallaFault", Name="UsuarioFalla", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
        bool YaIniciadoSesion(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/YaIniciadoSesion", ReplyAction="http://tempuri.org/IServicioUsuario/YaIniciadoSesionResponse")]
        System.Threading.Tasks.Task<bool> YaIniciadoSesionAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Ping", ReplyAction="http://tempuri.org/IServicioUsuario/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Ping", ReplyAction="http://tempuri.org/IServicioUsuario/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ValidarCredenciales", ReplyAction="http://tempuri.org/IServicioUsuario/ValidarCredencialesResponse")]
        WpfCliente.ServidorDescribelo.Usuario ValidarCredenciales(string gamertag, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ValidarCredenciales", ReplyAction="http://tempuri.org/IServicioUsuario/ValidarCredencialesResponse")]
        System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.Usuario> ValidarCredencialesAsync(string gamertag, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/EditarContraseniaUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/EditarContraseniaUsuarioResponse")]
        bool EditarContraseniaUsuario(string gamertag, string nuevoHashContrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/EditarContraseniaUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/EditarContraseniaUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EditarContraseniaUsuarioAsync(string gamertag, string nuevoHashContrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : WpfCliente.ServidorDescribelo.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioUsuario>, WpfCliente.ServidorDescribelo.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EditarUsuario(WpfCliente.ServidorDescribelo.Usuario usuarioEditado) {
            return base.Channel.EditarUsuario(usuarioEditado);
        }
        
        public System.Threading.Tasks.Task<bool> EditarUsuarioAsync(WpfCliente.ServidorDescribelo.Usuario usuarioEditado) {
            return base.Channel.EditarUsuarioAsync(usuarioEditado);
        }
        
        public bool YaIniciadoSesion(string nombreUsuario) {
            return base.Channel.YaIniciadoSesion(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> YaIniciadoSesionAsync(string nombreUsuario) {
            return base.Channel.YaIniciadoSesionAsync(nombreUsuario);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public WpfCliente.ServidorDescribelo.Usuario ValidarCredenciales(string gamertag, string contrasenia) {
            return base.Channel.ValidarCredenciales(gamertag, contrasenia);
        }
        
        public System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.Usuario> ValidarCredencialesAsync(string gamertag, string contrasenia) {
            return base.Channel.ValidarCredencialesAsync(gamertag, contrasenia);
        }
        
        public bool EditarContraseniaUsuario(string gamertag, string nuevoHashContrasenia) {
            return base.Channel.EditarContraseniaUsuario(gamertag, nuevoHashContrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> EditarContraseniaUsuarioAsync(string gamertag, string nuevoHashContrasenia) {
            return base.Channel.EditarContraseniaUsuarioAsync(gamertag, nuevoHashContrasenia);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioUsuarioSesion", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioUsuarioSesionCallback))]
    public interface IServicioUsuarioSesion {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioUsuarioSesion/ObtenerSessionJugador")]
        void ObtenerSessionJugador(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioUsuarioSesion/ObtenerSessionJugador")]
        System.Threading.Tasks.Task ObtenerSessionJugadorAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioSesionCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarioSesion/ObtenerSessionJugadorCallback", ReplyAction="http://tempuri.org/IServicioUsuarioSesion/ObtenerSessionJugadorCallbackResponse")]
        void ObtenerSessionJugadorCallback(bool esSesionAbierta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioSesionChannel : WpfCliente.ServidorDescribelo.IServicioUsuarioSesion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioSesionClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioUsuarioSesion>, WpfCliente.ServidorDescribelo.IServicioUsuarioSesion {
        
        public ServicioUsuarioSesionClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioUsuarioSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioUsuarioSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioSesionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioSesionClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ObtenerSessionJugador(WpfCliente.ServidorDescribelo.Usuario usuario) {
            base.Channel.ObtenerSessionJugador(usuario);
        }
        
        public System.Threading.Tasks.Task ObtenerSessionJugadorAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.ObtenerSessionJugadorAsync(usuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioInvitacionPartida", CallbackContract=typeof(WpfCliente.ServidorDescribelo.IServicioInvitacionPartidaCallback))]
    public interface IServicioInvitacionPartida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInvitacionPartida/EnviarInvitacion", ReplyAction="http://tempuri.org/IServicioInvitacionPartida/EnviarInvitacionResponse")]
        bool EnviarInvitacion(string gamertagEmisor, string codigoSala, string gamertagReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInvitacionPartida/EnviarInvitacion", ReplyAction="http://tempuri.org/IServicioInvitacionPartida/EnviarInvitacionResponse")]
        System.Threading.Tasks.Task<bool> EnviarInvitacionAsync(string gamertagEmisor, string codigoSala, string gamertagReceptor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioInvitacionPartida/AbrirCanalParaInvitaciones")]
        void AbrirCanalParaInvitaciones(WpfCliente.ServidorDescribelo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioInvitacionPartida/AbrirCanalParaInvitaciones")]
        System.Threading.Tasks.Task AbrirCanalParaInvitacionesAsync(WpfCliente.ServidorDescribelo.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioInvitacionPartidaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioInvitacionPartida/RecibirInvitacion")]
        void RecibirInvitacion(WpfCliente.ServidorDescribelo.InvitacionPartida invitacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioInvitacionPartidaChannel : WpfCliente.ServidorDescribelo.IServicioInvitacionPartida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInvitacionPartidaClient : System.ServiceModel.DuplexClientBase<WpfCliente.ServidorDescribelo.IServicioInvitacionPartida>, WpfCliente.ServidorDescribelo.IServicioInvitacionPartida {
        
        public ServicioInvitacionPartidaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioInvitacionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioInvitacionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInvitacionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInvitacionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool EnviarInvitacion(string gamertagEmisor, string codigoSala, string gamertagReceptor) {
            return base.Channel.EnviarInvitacion(gamertagEmisor, codigoSala, gamertagReceptor);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarInvitacionAsync(string gamertagEmisor, string codigoSala, string gamertagReceptor) {
            return base.Channel.EnviarInvitacionAsync(gamertagEmisor, codigoSala, gamertagReceptor);
        }
        
        public void AbrirCanalParaInvitaciones(WpfCliente.ServidorDescribelo.Usuario usuario) {
            base.Channel.AbrirCanalParaInvitaciones(usuario);
        }
        
        public System.Threading.Tasks.Task AbrirCanalParaInvitacionesAsync(WpfCliente.ServidorDescribelo.Usuario usuario) {
            return base.Channel.AbrirCanalParaInvitacionesAsync(usuario);
        }
    }
}
