//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCliente.ServidorDescribelo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatUsuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class ChatUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreHospedadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionIP {
            get {
                return this.DireccionIPField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionIPField, value) != true)) {
                    this.DireccionIPField = value;
                    this.RaisePropertyChanged("DireccionIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreHospedador {
            get {
                return this.NombreHospedadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreHospedadorField, value) != true)) {
                    this.NombreHospedadorField = value;
                    this.RaisePropertyChanged("NombreHospedador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMensaje", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioLibreria.Modelo")]
    [System.SerializableAttribute()]
    public partial class ChatMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCliente.ServidorDescribelo.ChatUsuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoraFecha {
            get {
                return this.HoraFechaField;
            }
            set {
                if ((this.HoraFechaField.Equals(value) != true)) {
                    this.HoraFechaField = value;
                    this.RaisePropertyChanged("HoraFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCliente.ServidorDescribelo.ChatUsuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioRegistro")]
    public interface IServicioRegistro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistro/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistro/RegistrarUsuarioResponse")]
        int RegistrarUsuario(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistro/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistro/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string usuario, string contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRegistroChannel : WpfCliente.ServidorDescribelo.IServicioRegistro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistroClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioRegistro>, WpfCliente.ServidorDescribelo.IServicioRegistro {
        
        public ServicioRegistroClient() {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarUsuario(string usuario, string contrasenia) {
            return base.Channel.RegistrarUsuario(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string usuario, string contrasenia) {
            return base.Channel.RegistrarUsuarioAsync(usuario, contrasenia);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDescribelo.IServicioChat")]
    public interface IServicioChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ConectarUsuario", ReplyAction="http://tempuri.org/IServicioChat/ConectarUsuarioResponse")]
        WpfCliente.ServidorDescribelo.ChatUsuario ConectarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ConectarUsuario", ReplyAction="http://tempuri.org/IServicioChat/ConectarUsuarioResponse")]
        System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatUsuario> ConectarUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ObtenerUsuariosConectados", ReplyAction="http://tempuri.org/IServicioChat/ObtenerUsuariosConectadosResponse")]
        WpfCliente.ServidorDescribelo.ChatUsuario[] ObtenerUsuariosConectados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ObtenerUsuariosConectados", ReplyAction="http://tempuri.org/IServicioChat/ObtenerUsuariosConectadosResponse")]
        System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatUsuario[]> ObtenerUsuariosConectadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/EnviarMensaje", ReplyAction="http://tempuri.org/IServicioChat/EnviarMensajeResponse")]
        void EnviarMensaje(WpfCliente.ServidorDescribelo.ChatMensaje nuevoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/EnviarMensaje", ReplyAction="http://tempuri.org/IServicioChat/EnviarMensajeResponse")]
        System.Threading.Tasks.Task EnviarMensajeAsync(WpfCliente.ServidorDescribelo.ChatMensaje nuevoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/GetMensajeNuevo", ReplyAction="http://tempuri.org/IServicioChat/GetMensajeNuevoResponse")]
        WpfCliente.ServidorDescribelo.ChatMensaje[] GetMensajeNuevo(WpfCliente.ServidorDescribelo.ChatUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/GetMensajeNuevo", ReplyAction="http://tempuri.org/IServicioChat/GetMensajeNuevoResponse")]
        System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatMensaje[]> GetMensajeNuevoAsync(WpfCliente.ServidorDescribelo.ChatUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/DesconectarUsuario", ReplyAction="http://tempuri.org/IServicioChat/DesconectarUsuarioResponse")]
        void DesconectarUsuario(WpfCliente.ServidorDescribelo.ChatUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/DesconectarUsuario", ReplyAction="http://tempuri.org/IServicioChat/DesconectarUsuarioResponse")]
        System.Threading.Tasks.Task DesconectarUsuarioAsync(WpfCliente.ServidorDescribelo.ChatUsuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatChannel : WpfCliente.ServidorDescribelo.IServicioChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatClient : System.ServiceModel.ClientBase<WpfCliente.ServidorDescribelo.IServicioChat>, WpfCliente.ServidorDescribelo.IServicioChat {
        
        public ServicioChatClient() {
        }
        
        public ServicioChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfCliente.ServidorDescribelo.ChatUsuario ConectarUsuario(string usuario) {
            return base.Channel.ConectarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatUsuario> ConectarUsuarioAsync(string usuario) {
            return base.Channel.ConectarUsuarioAsync(usuario);
        }
        
        public WpfCliente.ServidorDescribelo.ChatUsuario[] ObtenerUsuariosConectados() {
            return base.Channel.ObtenerUsuariosConectados();
        }
        
        public System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatUsuario[]> ObtenerUsuariosConectadosAsync() {
            return base.Channel.ObtenerUsuariosConectadosAsync();
        }
        
        public void EnviarMensaje(WpfCliente.ServidorDescribelo.ChatMensaje nuevoMensaje) {
            base.Channel.EnviarMensaje(nuevoMensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(WpfCliente.ServidorDescribelo.ChatMensaje nuevoMensaje) {
            return base.Channel.EnviarMensajeAsync(nuevoMensaje);
        }
        
        public WpfCliente.ServidorDescribelo.ChatMensaje[] GetMensajeNuevo(WpfCliente.ServidorDescribelo.ChatUsuario usuario) {
            return base.Channel.GetMensajeNuevo(usuario);
        }
        
        public System.Threading.Tasks.Task<WpfCliente.ServidorDescribelo.ChatMensaje[]> GetMensajeNuevoAsync(WpfCliente.ServidorDescribelo.ChatUsuario usuario) {
            return base.Channel.GetMensajeNuevoAsync(usuario);
        }
        
        public void DesconectarUsuario(WpfCliente.ServidorDescribelo.ChatUsuario usuario) {
            base.Channel.DesconectarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task DesconectarUsuarioAsync(WpfCliente.ServidorDescribelo.ChatUsuario usuario) {
            return base.Channel.DesconectarUsuarioAsync(usuario);
        }
    }
}
